language: node_js

node_js:
  - 10.16.2
  
sudo: required

branches:                   # 使用分支
  only:
   - master

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn install

script:
  - yarn build
